#!/usr/bin/env bash
set -ex

mkdir -p dist/
~/.local/share/nvim/mason/bin/lua-language-server --doc ./lua --doc_out_path ./dist

GENERATED_LOG_PATH="./dist/doc.md"
END_MARKER="^# _G"

END_LINE=$(grep -n "$END_MARKER" "$GENERATED_LOG_PATH" | cut -d: -f1 | head -n 1)
END_LINE=$((END_LINE - 1))

head -n "$END_LINE" "$GENERATED_LOG_PATH" > API.md
~/.local/share/nvim/mason/packages/prettier/node_modules/prettier/bin/prettier.cjs --write API.md
